'use strict'
main();

function coinOnTheTable(m, k, board) {
    const ROW_COUNT = board.length, COLUMN_COUNT = m, STAR = '*', MAX_NUMBER = 10000000;
    //                  left,    right,  up,      down                  
    const NEIGHBOURS = [[0, -1], [0, 1], [-1, 0], [1, 0]], NEIGHBOUR_LETTERS = ['L', 'R', 'U', 'D'];
    let resultIJK = [], END_ROW = board.findIndex(row => row.includes(STAR)), END_COLUMN = board[END_ROW].indexOf(STAR);

    // initialize the 3-dimensional array, i (row), j (column), time (the time spent in reach current location [i,j]), these 3 factors define the [min changes] value
    for (let i = 0; i < ROW_COUNT; i++) {
        let row = [];
        resultIJK.push(row);
        for (let j = 0; j < COLUMN_COUNT; j++)
            row[j] = [];
    }

    // only initialze the [min changes] value only when time === 0 
    for (let i = 0; i < ROW_COUNT; i++) {
        for (let j = 0; j < COLUMN_COUNT; j++) {
            let cellOfTime = resultIJK[i][j];
            cellOfTime[0] = ((i + j) === 0 ? 0 : MAX_NUMBER);
        }
    }

    // iterate time from 1 to k, also interate location (i,j)
    for (let time = 1; time <= k; time++) {
        for (let i = 0; i < ROW_COUNT; i++) {
            for (let j = 0; j < COLUMN_COUNT; j++) {
                let cellOfTime = resultIJK[i][j];

                let changeIJTime = MAX_NUMBER;
                for (let idx = 0; idx < NEIGHBOURS.length; idx++) {
                    let neighbour = NEIGHBOURS[idx], prevI = i - neighbour[0], prevJ = j - neighbour[1];
                    if (prevI >= 0 && prevI < ROW_COUNT && prevJ >= 0 && prevJ < COLUMN_COUNT) {
                        let prevChanges = resultIJK[prevI][prevJ][time - 1];
                        if (prevChanges !== undefined && prevChanges !== MAX_NUMBER)
                            changeIJTime = Math.min(changeIJTime, (board[prevI][prevJ] === NEIGHBOUR_LETTERS[idx] ? 0 : 1) + prevChanges);
                    }
                }
                cellOfTime[time] = changeIJTime;
            }
        }
    }

    let resultArr = resultIJK[END_ROW][END_COLUMN].filter(element => element !== undefined && element < MAX_NUMBER).sort((a, b) => a - b);
    return resultArr.length === 0 ? -1 : resultArr[0];
}

function main() {
    let inputs = [`3 3 5
    RRD
    DLL
    *UU`
        , `18 42 42
    DUDDDLLRURULLDLURURLDLRULDURLDDURLUURLURRU
    DLDLURDRRLDDLDULRUDURDDUURDLLLLRRLDUULLDDD
    RULURDLLUULDRDDLLDLRDUDRDDRRRDRUDRURURLRLD
    RLUDLLLUURRDRRDRDRLDLDDDULLRRLLRLDLUDRDDUU
    RDDRURLRUUDLLRLULLLLULLDLUDRLDRDDURDLRDRLL
    LDRDDDLDUDLDUDRLURRDLURRRDLDURLULDDURDUDLU
    UDUULDRUULUDL*UDULUDLLRRLULULUDULURLRDULLL
    UDLDRLDLDLRRULURDRUDRLDLLDDRLRRLRUURLUDULR
    RULDDLUULRRDRDLUULRULDRRUULULLUDRLLRLLDRRR
    ULRLDDDUUDLLRLURRURLDRULRRDUDRULUDDRDLULDD
    DDDRDRRULRLUUDRRDDLDUDRLRRRDLRDRLUDRULLLDR
    DUDULULRLUDRLRLLLUUURRDLLRRLLLDUDLDRDDURRR
    UULDRUULRDDRDLUDLLLULULRRUUUULDDDRRRUDLLDU
    LLLURRRDRUUULDLLLDDDLLRLDLLURUDLRLDLDDLLUL
    LLLDDDDULDRURULULLULLUDRDURRRRUUURRLURDURL
    RDDDDDLRRRRLRUDRLURRLRRUUUUURULULRRDRUUDUU
    RDUURUULLDULRUULRRLLDDLRURDULRDLUDDDURDRUD
    LUDLDDRDURUDLLLDRLRRRLRDULLLDLDUUUDRRDRLRU`
        , `50 50 4
    RURDRDRLDLUDLDURURRDDLLLURLUDRRRUDRDLULDRRULDLDDRL
    RRRURDULDLRRLURDRDURUDDDDRURUUUULUULLDDUUUULURURRU
    URLDDRRDDLRDLLRRUURDLDRURUDUDDLDLDUUDDLLDRRDDRDLRR
    RLLRRLUDRDULLDLDRLLRULRDRRDRRDDRLDLDURUUULLDURLDLD
    LDUULRRLRUUDDLLDLDULULUUURRDRDUDLLRLRDLDLRRLDLUURD
    LRRDRLRURDRDRUUUUDRLDUDDLRULRUDLLRLRDRLUDRLRLLLDUU
    LDULDRLURDULUURUDULDUUDLLDURDUULRLDDRLRUDRRLURULLL
    UDDLRDDUDUDDLDULRUDLUDLUULLLUDRLUDDLLLUULDURDRULRL
    RLLLULDURDULRDLLRRURLDDLUUDRUUUUURUURDURDULUDDULRD
    LUUUURRURLUDRURLLDDLLUDDRLLRURULUULULRURLDUUUURRUD
    UDLDURDUULRLDURLLLLURDLLRLDULRURRRLUDURURRDLULDRDL
    DURRLUDUULLLLULURLURDLRRUDRLLRDLURDLLUDUUURLLLDRDD
    RDDLULLLLDRDUDUDULLURLDDRDRLLDLULDULLDULRUULUUDLUD
    LRRRUDRUULUUDLDULDDLUUUURLDDLULDDLLDUDDLLLRUDDLLDU
    UULLDRDRRLRDUULDRULDULRRLDUULDURUDUURLRLRDRURRLDDD
    DLDLDLLDRULUURLUUUUUUDDRULDURLRLLUDRURLRULRRUDDUDL
    LDDULRLURRDDUDDLUDDUDUDDDLRLLLUURLURLLRRULLLRDRRLU
    LUUULLDLDRLRLULRUUDRRUDRLUDUDUDRLUUURLURUUDDULDRUD
    LDLDRDDLLDDLUULULULDDDLRDLDULDDLLLDRDRDRRDLLRLDUDR
    ULURUDRLLDLRDLDURUDUURDLRRULDLLDURRLDULLRULLLLULLL
    RRDULLDLUUDURDRULURURULUDRRUURLLUUURLDDRRLRLDULUUR
    RDDRURLULUDULUUDDDULRDLLDUULDLRDLLULDUUDRDDLDRDDDD
    DLLRRDLDRRLRDRDDUUDLLLRULRRDDDLUURRRURRRDDLDDLDDLU
    LRRLDDLDRDRLDDULLRDDLRLRULDLRRULLDDRDRDULRDUDRRLRR
    UUDDLDLDUDUDDUULDDLUDLLDUULLULRLDURRUUUDLRDRLRLLLU
    LRLLRRUDLLRDLLRRUDRRULRDRDDUUDRULRRURLDLDRRLRLDLDD
    URRDRDDUDUDURLLDDLRDLUULUULLRDDRDDLDLDRRDUDRDLDUUD
    RURRRLLDULUDRRRRUDLUDULUULUDRLRUDDRLDUDDLRULUURRRL
    LLRUULUUUUDURLLRLDLLLDULURRLRDULDLDURLRURLUUDDLUUD
    RLLRLULRDUULRLUULLULDRRLURDRUDLDUUDUDRDRRDRLLULLDU
    LDDLLDLURRRRRLLLUDDDUURLURRDDRUDDUDLLRUDDULUULDRRU
    RRLDURLLDDRUUDUURUURURUDDULDLULUUDDUUUDDRRLRUDDLLR
    RDLDURULDRDLDDURDUUDLLRDDURLULLDDRLLURULDURRLRDDLR
    DUUURLURLRULDLLRURLDDUUDLRLLRRLDDLRRDRRDDURDRURRUD
    RURLLRLDDUURUDDUDLURDLRDRDURUDLUDLRRDUUURLRLDLURUD
    RLLDUULURLLRLDDDLLULDDDLRRLDRDURLDDDDULDLDUDLDULUD
    RURLUUDULRUURURRLDDUULDRUDLDDRRRRRLDDLDLRDLLRLRRDR
    LRUUUDLUUDRRRRLLLRLLRUURLRRLLUDUULRRRUURRR*LRLLRDD
    URRLDUDDLRLURDULLURLLDRDRURDLULDLLRRDDURRDDRULDLDL
    RLDRDRUUDURDDLLLULLLDLULRLDDLLRLUDULLLDDLURULUULUL
    RLRRLLDRLRRRDRDURRLDRDLLDLLDDLUULURUURLRUDRUUDDLUD
    UDLURRULDULUDDRDRRLDRRDDURLURDDDDDLLLRUDLUUDLULUDU
    URRLDRLDUULLLRLRUDDRULLRLLDURDUUULUULUDDLLDRURRRLD
    LDDDLDDRRDLUDDDRLLUULDDUDUDDDULURRLRLLUUDLDDRDRDRR
    UDDDDULRULUUDLLRUDULRDLRULLLURURUUDLLRLLDRURRRRRDD
    LULUDLDLDDRRLDURUUULDLURRUUDUDLUURDRDLRRRLDRDDRDUD
    RUULRUDRRLULDDUDDDULLLDRULUDRLLLRDRUURLLDLRDDRLUUD
    URDULDDURLLLLDDDLURRRLRULRLLDLUDDRRRULRRRRLLDLUUDL
    LLLDLURUDLDRURRLDDLDLLURUDRDUDLDRRLRDLUUDLULULUULU
    LLURLDUULUURULLLDURRUUUDLUDLRURULDLUURRRULURRRLULD`
        , `20 17 47
    DRLULLRRRLRDLRRLU
    URUURLRLLLDULRRRR
    DRDLDDLDRRDRURRLR
    DRRRRRRLDULDDUDLD
    DULRDDULDUDULRDUD
    LRURUDURRUURDDUDL
    URURDLRUULRRDLDLR
    DLRUDLDRUUDULUDUU
    *ULLURDRDUURLDRDR
    ULDUDUUULLURURURR
    LDRDLDRRLDDRRLRLD
    RDDLURRRDDLRDURLD
    ULRLRLRRLLLRRURRL
    RLLLDRDURLRURLUDD
    DRLDURRLURUULLRDU
    RURRUDLLLDDDRUUUD
    UUUUDDLRURULRRDRD
    URDUUDRDLDRLLULRU
    DRDUUULUUDURULDDL
    LLULDRLRRRUDLDRRU`
        , `2 2 3  
    RD  
    *L`,
        `2 2 1  
    RD  
    *L`]; for (let i = 0; i < inputs.length; i++) {        // inputs.length
        let input = inputs[i], lines = input.split('\n').map(s => s.trim()).filter(s => s !== ''), index = 0;

        const nmk = lines[index++].split(' '), n = parseInt(nmk[0], 10), m = parseInt(nmk[1], 10), k = parseInt(nmk[2], 10);

        let board = [];
        for (let boardItr = 0; boardItr < n; boardItr++) {
            const boardItem = lines[index++];
            board.push(boardItem);
        }

        let result = coinOnTheTable(m, k, board);
        console.log(result);
    }
}
